### ISSUE TITLE
dll loading error (randomly)

### ISSUE THREAD

**Issue by marcomezzanotte** [elyor0529/NpgsqlBulkCopy#1]
Hi, we're randomly experiencing the following error: 

`Unable to load DLL 'PgCPP.DLL.9.x.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E) -    at Npgsql.BulkCopy.Native.Versions.PQ9xNativeApi.openRemoteConn(Char hostaddr, Int32 port, Char dbname, Char user, Char password)
   at Enerj.CDV.Data.DataManagerBase`1.InsertBulk(DataTable DT_Tabella)
   at Enerj.CDV.Data.DataManager.IndicizzaDocumentInstance(List`1 ListID, Int64 IDInstance)
   at Enerj.CDV.ControlsService.Manager.StartProcess()`

The library is used in a Windows Service and the error shows after deploy and installation, while everything works fine in Visual Studio. On the server where we deploy the service, we've installed the Visual C++ Redistributable.

We hope you can give us a hint or a solution for this problem.

Thank you.

**Comment by uzbekdev1** [comment]
Hi! 
Okay I'll tomorrow  look it

**Comment by uzbekdev1** [comment]
which version your PG ? 9.5 or 9.4?
Need to update from C:\Program Files\PostgreSQL\9.5 folder lib & dll's

**Comment by marcomezzanotte** [comment]
Sorry but I don't understand.

When I download the Nuget package, a folder named lipqdll with the following structure is downloaded and what I do is to copy the whole folder structure and contents to the service deployed root folder.

![ad3ef972536ad54cdef7b8f78381b50c9d49a0daac049d4e03 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/6223581/15139242/32216266-1695-11e6-8522-af2ac3f26938.png)

Am I wrong?
What am I supposed to do exactly?

**Comment by nonoantog** [comment]
I have the same problem. My postgres instance is on linux server.

**Comment by nicusorserban** [comment]
How we can get past this error?
I've tried to compile the .DLL but it gives me countless errors ...

**Comment by screig** [comment]
Same issue, note im running under Net Core

**Comment by uzbekdev1** [comment]
Ok, looking today.End of this week I pushed a new version.

**Comment by Steven-FlexTechs** [comment]
I have the exact same error. I am using PG 9.5. It all works fine for my unit test project. 

I get the `Unable to load DLL 'PgCPP.DLL.9.x.dll': The specified module could not be found.` error for my MVC web project. Same computer, same database.

I tried adding the `lipqDLL` folder to the bin folder which worked for my Unit Test project. Did not work still.

I wish the error said the expected directory too so I know where to put the dlls: `Unable to load DLL 'C:/Project Folder/bin/PgCPP.DLL.9.x.dll': The specified module could not be found.`

**Comment by uzbekdev1** [comment]
Hi!
Thank you for your replying.

Last 2 week I have many works because I don't have nay time.
This week I can be looked.

**Comment by officer-rosmarino** [comment]
Same problem here, but for me it doesn't work even on Visual Studio.

**Comment by screig** [comment]
I fixed it, I will make a pull request today to merge 

I also then want to go on and use costura to embedded the C++ dlls in the Net assembly

**Comment by officer-rosmarino** [comment]
@screig waiting for it, thanks

**Comment by screig** [comment]
Ok I have reworked the code base quite a bit

[forked version](https://github.com/screig/NpgsqlBulkCopy)

The C++ projects had hard-coded links to specific installed versions of Postgres. I have made all the C++ projects use relative paths.  I also went and tried to go and find the required references, namely the lib and include files for the following versions:

- 9.x x86
- 9.x x64
- 8.x x86
- 8.x x64 (this one I could not find)

I included this data in the code base (bar 8.x x64). I rebuilt the C++ projects which regenerated the missing dlls and copied them over to the C# folder.

**Comment by officer-rosmarino** [comment]
@screig could you please point out where you did the changes?

**Comment by screig** [comment]
sorry it is still uploading...

![image](https://cloud.githubusercontent.com/assets/4292074/26628880/d1a69f44-45f7-11e7-8772-360dc5badbb0.png)

**Comment by elyor0529** [comment]
Let me check I enable now

**Comment by uzbekdev1** [comment]
Thank you!

**Comment by screig** [comment]
Ok its in

**Comment by screig** [comment]
If anybody can find the x64 version of the postgres binaries I can add them in

**Comment by uzbekdev1** [comment]
thanks🤗
